const OPTIONS_NAME = {
  OPTION0: "clock",
  OPTION1: "pendulum",
  OPTION2: "tree",
  OPTION3: "cup",
  OPTION4: "saltAndPepper",
  OPTION5: "headphones",
  OPTION6: "vacum",
  OPTION7: "globe",
  OPTION8: "fan",
  OPTION9: "frame",
  OPTION10: "small_headphones",
  OPTION11: "wallet",
  OPTION12: "snow_globe",
  OPTION13: "gold_tree",
  OPTION14: "picnic_box",
  OPTION15: "dollar4",
  OPTION16: "dollar5",
  OPTION17: "dollar8",
  OPTION18: "dollar9",
};
const OPTIONS = {
  OPTION0: `/assets/${OPTIONS_NAME.OPTION0}.png`,
  OPTION1: `/assets/${OPTIONS_NAME.OPTION1}.png`,
  OPTION2: `/assets/${OPTIONS_NAME.OPTION2}.png`,
  OPTION3: `/assets/${OPTIONS_NAME.OPTION3}.png`,
  OPTION4: `/assets/${OPTIONS_NAME.OPTION4}.png`,
  OPTION5: `/assets/${OPTIONS_NAME.OPTION5}.png`,
  OPTION6: `/assets/${OPTIONS_NAME.OPTION6}.png`,
  OPTION7: `/assets/${OPTIONS_NAME.OPTION7}.png`,
  OPTION8: `/assets/${OPTIONS_NAME.OPTION8}.png`,
  OPTION9: `/assets/${OPTIONS_NAME.OPTION9}.png`,
  OPTION10: `/assets/${OPTIONS_NAME.OPTION10}.png`,
  OPTION11: `/assets/${OPTIONS_NAME.OPTION11}.png`,
  OPTION12: `/assets/${OPTIONS_NAME.OPTION12}.png`,
  OPTION13: `/assets/${OPTIONS_NAME.OPTION13}.png`,
  OPTION14: `/assets/${OPTIONS_NAME.OPTION14}.png`,
  OPTION15: `/assets/${OPTIONS_NAME.OPTION15}.png`,
  OPTION16: `/assets/${OPTIONS_NAME.OPTION16}.png`,
  OPTION17: `/assets/${OPTIONS_NAME.OPTION17}.png`,
  OPTION18: `/assets/${OPTIONS_NAME.OPTION18}.png`,
};

export { OPTIONS, OPTIONS_NAME };
